# Generated by Django 2.0.7 on 2020-05-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('classNo', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='班级编号')),
                ('className', models.CharField(max_length=45, verbose_name='班级名称')),
                ('classBrief', models.CharField(max_length=30, verbose_name='班级简称')),
                ('classNumber', models.IntegerField(default=0, verbose_name='人数')),
                ('girlNumber', models.IntegerField(default=0, verbose_name='女生人数')),
                ('schoolDate', models.DateField(verbose_name='入学时间')),
                ('studyTime', models.IntegerField(verbose_name='学制')),
                ('classState', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '班级信息表',
                'verbose_name_plural': '班级信息表',
            },
        ),
        migrations.CreateModel(
            name='DepInfo',
            fields=[
                ('departNo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='部门编号')),
                ('depart', models.CharField(max_length=36, verbose_name='部门名称')),
                ('departBrief', models.CharField(max_length=27, verbose_name='部门简称')),
                ('departInfo', models.CharField(max_length=90, verbose_name='部门描述')),
                ('depNumber', models.IntegerField(default=0, verbose_name='人数')),
                ('girlNumber', models.IntegerField(default=0, verbose_name='女生人数')),
                ('freNumber', models.IntegerField(default=0, verbose_name='大一人数')),
                ('sopNumber', models.IntegerField(default=0, verbose_name='大二人数')),
                ('junNumber', models.IntegerField(default=0, verbose_name='大三人数')),
                ('senNumber', models.IntegerField(default=0, verbose_name='大四人数')),
                ('depState', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '学院部门信息表',
                'verbose_name_plural': '学院部门信息表',
            },
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('majorNo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='专业编号')),
                ('major', models.CharField(max_length=60, verbose_name='专业方向')),
                ('MajorShort', models.CharField(max_length=45, verbose_name='简称')),
                ('departNo', models.CharField(max_length=4, verbose_name='部门编码')),
                ('majorInfo', models.CharField(max_length=150, verbose_name='专业描述')),
                ('marjorNumber', models.IntegerField(default=0, verbose_name='人数')),
                ('majorState', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '专业信息表',
                'verbose_name_plural': '专业信息表',
            },
        ),
        migrations.CreateModel(
            name='PoliticalStatus',
            fields=[
                ('politicalNo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='政治面貌编码')),
                ('politicalName', models.CharField(max_length=24, verbose_name='政治面貌编码')),
            ],
            options={
                'verbose_name': '政治面貌表',
                'verbose_name_plural': '政治面貌表',
            },
        ),
        migrations.CreateModel(
            name='StuBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=18, verbose_name='姓名')),
                ('birthday', models.DateTimeField(verbose_name='出生日期')),
                ('ClassName', models.CharField(max_length=30, verbose_name='班级')),
                ('major', models.CharField(max_length=30, verbose_name='专业方向')),
                ('college', models.CharField(max_length=30, verbose_name='学院')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('nation', models.CharField(max_length=30, verbose_name='名族')),
                ('hometown', models.CharField(max_length=84, verbose_name='籍贯')),
                ('political', models.CharField(max_length=24, verbose_name='政治面貌')),
                ('idcard', models.CharField(max_length=18, verbose_name='身份证号')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='个人邮箱')),
                ('emailOnly', models.IntegerField(verbose_name='邮箱绑定')),
                ('family', models.CharField(blank=True, max_length=30, null=True, verbose_name='家庭联系人')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='家庭地址')),
                ('fphone', models.CharField(blank=True, max_length=18, null=True, verbose_name='家庭联系电话')),
                ('photo', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='照片')),
                ('eduBackground', models.CharField(blank=True, max_length=12, null=True, verbose_name='学历')),
                ('englishlevel', models.CharField(blank=True, max_length=12, null=True, verbose_name='英语等级')),
                ('bankcard', models.CharField(blank=True, max_length=25, null=True, verbose_name='银行卡号')),
                ('exameState', models.CharField(blank=True, max_length=30, null=True, verbose_name='审核状态')),
                ('remarks', models.CharField(blank=True, max_length=150, null=True, verbose_name='备注')),
                ('stuState', models.IntegerField(verbose_name='状态')),
                ('ClassNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentMessage.ClassInfo', verbose_name='班级编号')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_stu', to='MainApp.StuInfo', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生基本信息表',
                'verbose_name_plural': '学生基本信息表',
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='majorNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentMessage.MajorInfo', verbose_name='专业编号'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='teacherNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.TecInfo', verbose_name='老师编号'),
        ),
    ]
