# Generated by Django 2.0.7 on 2020-05-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stubasicinfo',
            name='ClassNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cla', to='StudentMessage.ClassInfo', verbose_name='班级编号'),
        ),
    ]
