# Generated by Django 2.0.7 on 2020-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMessage', '0002_auto_20200514_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stubasicinfo',
            name='emailOnly',
            field=models.IntegerField(default=0, verbose_name='邮箱绑定'),
        ),
        migrations.AlterField(
            model_name='stubasicinfo',
            name='stuState',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
